# Generated by Django 3.2.5 on 2022-01-29 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 29, 14, 35, 34, 494293, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 29, 14, 36, 16, 159516, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
